### ISSUE TITLE
not work in my side

### ISSUE THREAD

**Issue by zhiwzhao** [rishabh9/mdc-propagation-dispatcher#1]
below is log, 

10:53:10.192 [info] akka.event.slf4j.Slf4jLogger - - Slf4jLogger started
10:53:10.204 [info] controllers.HomeController 27ece190-b287-4a87-8f15-9a48d6de10d8 - enter timecost
10:53:10.204 [info] controllers.HomeController 27ece190-b287-4a87-8f15-9a48d6de10d8 - enter callFUN start
10:53:10.205 [info] controllers.HomeController - - work callfun 
10:53:15.209 [info] controllers.HomeController - - work callfun end
10:53:15.209 [info] controllers.HomeController - - call callFunc:OK

the UUID is not present in another thread

**Comment by rishabh9** [comment]
@zhiwzhao The information provided is not sufficient for me to debug. Could you provide me with more details like:
- Are you using the Play's default thread pool through out?
- (Where required) are you using the [HttpExecutionContext](https://www.playframework.com/documentation/2.5.x/api/java/play/libs/concurrent/HttpExecutionContext.html) as mentioned [here](https://www.playframework.com/documentation/2.5.x/ThreadPools)
- Could you share some sample code?

**Comment by smur89** [comment]
Hey rishabh9,

I'm having a similar issue here with this approach as zhiqzhao, was wondering if you could help?

I've got a sample app running here where the issue is replicated.
https://github.com/smur89/MDCSampleApp

```XML
      <pattern>%d{ISO8601} [%-5level] %-60([%thread] %logger{5}) %mdc{X-UUID:--} - %msg%n%ex{20}</pattern>
```
```
2017-06-12 16:01:49,944 [INFO ] [ForkJoinPool-1-worker-9] application                        - - ApplicationTimer demo: Starting application at 2017-06-12T15:01:49.939Z.
2017-06-12 16:01:50,051 [INFO ] [application-akka.actor.default-dispatcher-5] a.e.s.Slf4jLogger - - Slf4jLogger started
2017-06-12 16:01:50,060 [INFO ] [ForkJoinPool-1-worker-9] p.a.Play                           - - Application started (Dev)
2017-06-12 16:01:50,109 [INFO ] [application-akka.actor.default-dispatcher-5] c.HomeController - - Logging
2017-06-12 16:01:50,111 [INFO ] [ForkJoinPool-3-worker-15] c.HomeController                  - - Logging in the Future!
```

I would expect The last two log statements here to have Request Ids associated with them. I've attempted to implement this MDC logging using both the Akka Dispatcher and ExecutionContext approaches, and both result in the same outcome.

Any help appreciated! Thanks

**Comment by rishabh9** [comment]
Thanks @smur89 for the sample app. I'll take a look and get back to you guys.

**Comment by rishabh9** [comment]
I have spent whole two days on this already and don't have an answer/solution yet. Will keep you updated.

**Comment by smur89** [comment]
Just saw your reply @rishabh9, thanks for taking the time to have a look.

**Comment by scozv** [comment]
hi all, I found the solution for tracking id missing, and created this PR to @smur89 's demo repo.

That is a simple code change, but toke me some time to investigate. Anyway I started to log the tracking id on my owned project. this is a good news.

**Comment by rishabh9** [comment]
@scozv Thanks for the update! Really appreciate it. I will try the changes on my side as well and update you all. :)

**Comment by smur89** [comment]
Thanks @scozv, I have tried this out in a branch and it solved my issues :1st_place_medal:
