### ISSUE TITLE
MDC context propagation is not working in play 2.6

### ISSUE THREAD

**Issue by mykhailov-egnaroinc** [rishabh9/mdc-propagation-dispatcher#2]
Hello,

[This](https://github.com/rishabh9/mdc-propagation-dispatcher/blob/master/src/main/scala/com/github/rishabh9/MDCPropagatingDispatcherConfigurator.scala) thread context propagation approach is not working if adding it as separate jar to classpath of client project (as described in caveats [here](https://github.com/jroper/thread-local-context-propagation/blob/master/README.md)). 
This config is added from client project side (note that play section is removed as discussed [there](https://github.com/jroper/thread-local-context-propagation/issues/1)).

```
akka {
  actor {
    default-dispatcher = {
      type = "mdc.MDCPropagatingDispatcherConfigurator"
    }
  }
}
```

Tested this cases:

1) MDC propagation between http filter and http controller
2) MDC propagation between http controller and akka actor
3) MDC propagation between actors
4) MDC propagation between http controller and async thread

All the above cases with give configuration are not working. In fact, in case of adding custom dispatcher configuration to target project itself, only propagation between http filter and http controller is floatingly working (for some reason works only in debug mode). 

Could you please point me out if I'm missing something?

Thanks in advance

**Comment by rishabh9** [comment]
Hi @mykhailov-egnaroinc,

I am sorry I cannot help you with this at the moment. It has been 2-3 years and I don't remember much about the implementation now. Also, this worked on Play 2.3/2.4. But, as far as I remember your configuration seems correct. I do remember one another thing, passing context between actors was a pain and that it was needed to be done manually.

I hope you have taken a look at #1 and at [this](https://scozv.github.io/blog/pattern/2017/07/18/injection-of-tracking-id-to-logback-message-with-customer-dispatcher-and-mapped-diagnostic-contexts-in-scala). It might give you some more inputs.

**Comment by mykhailov-egnaroinc** [comment]
Hi @rishabh9 
Managed to fix the issues by having custom execution context like [this](https://pastebin.com/R9ve2Pyh)

Then creating Actor System with custom execution context like:
`ActorSystem
      .create("customActorSystem", null, null,
          MDCHttpExecutionContext.fromThread(play.api.libs.concurrent.Execution.defaultContext()))`

After that one can instantiate actors via custom actor system via actorOf method.

For async computation, custom executor should be specified:
`return CompletableFuture.supplyAsync(() -> {
//... business logic
    }, MDCHttpExecutionContext.fromThread(play.api.libs.concurrent.Execution.defaultContext()))`

Hope it will help someone
Thanks,
Mykhailo
