### ISSUE TITLE
Scala 2.12 & Play 2.7

### ISSUE THREAD

**Issue by hwildwood** [rishabh9/mdc-propagation-dispatcher#3]
If this project is still maintained would it be possible to get a release for Scala 2.12 and Play 2.7?

**Comment by hwildwood** [comment]
PR - https://github.com/rishabh9/mdc-propagation-dispatcher/pull/4

**Comment by rishabh9** [comment]
@HerbiePorter Not maintained anymore. I'll merge your PR and try publishing a new build.

**Comment by rishabh9** [comment]
@HerbiePorter This is available as 0.0.7-SNAPSHOT on the Maven snapshot repository - https://oss.sonatype.org/#nexus-search;quick~mdc-propagation-dispatcher
If this works for you, let me know and I'll close this issue and move into Maven Release repository.
If it doesn't, then I'll revert the PR.

**Comment by rishabh9** [comment]
v0.0.7 available on release repository. Closing the ticket.
