### ISSUE TITLE
How to use classic MDC in Akka HTTP 

### ISSUE THREAD

**Issue by amerpersonal** [rishabh9/mdc-propagation-dispatcher#6]
Hi.

Can this dispatcher be used in Akka HTTP. I'm sending a message from web server to Actor using ask pattern. 

In web server, I'm including default ExecutionContext

`  implicit val ec = actorSystem.dispatchers.lookup("swipestox.activity-feed.dispatchers.mdc")
`

Then, I'm doing the same thing in Actor:

`   implicit val ec = actorSystem.dispatchers.lookup("swipestox.activity-feed.dispatchers.mdc")
`
Here is a definition of dispatcher:

```
mdc {
        type = "com.github.rishabh9.MDCPropagatingDispatcherConfigurator"
        executor = "fork-join-executor"
        fork-join-executor {
          parallelism-min = 2
          parallelism-factor = 2
          parallelism-max = 10
        }
        throughput = 100
      }
```

So, when I pass some variable to MDC before calling Actor:

`                MDC.put("req_id", requestId)
`

Writing that value in actor gives null:

`      logger.info(s"req id: ${MDC.get("req_id")}")
`

Can it work with Akka HTTP and Akka Actors in general, not just Play? Looking at the code, it can, but I can't manage do find a way...

**Comment by amerpersonal** [comment]
Any thought @rishabh9  ?

**Comment by rishabh9** [comment]
Apologies, I'm not in a position to help you here as I had set this up for
the play framework (Java) long ago. Also I think that Akka has undergone
some changes that may not allow this to work correctly now. You may want to
bring this up on other forums like stackoverflow, and maybe someone there
can help.

-Rishabh

**Comment by amerpersonal** [comment]
Ok, thank you!
